name: CI

on: [ push, pull_request ]

# Note: As of now the strategy property is not supported when using reusable workflows, so we can't use a build
# matrix to create the different build cases (see https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
jobs:
    build_1_4_230:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "v1.4.230"
            docker_version: '0'
            publish: true
            update_latest: false
            platforms: "linux/amd64"
    build_1_4_274:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "v1.4.274"
            docker_version: '0'
            publish: true
            update_latest: false
            platforms: "linux/amd64"
    build_1_4_287:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "v1.4.287"
            docker_version: '0'
            publish: true
            update_latest: false
            platforms: "linux/amd64"
    build_1_5_517:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "v1.5.517"
            docker_version: '0'
            publish: true
            update_latest: false
            platforms: "linux/amd64"
    build_latest:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "latest"
            docker_version: '0'
            publish: true
            update_latest: true
            platforms: "linux/amd64"
